from google.adk.tools.crewai_tool import CrewaiTool
from crewai_tools import RagTool

# Initialize RAG tool and add all SASB standards
rag_tool = RagTool()

# # Core SASB documents
# rag_tool.add(data_type="pdf_file", source="Standards/SASB-Conceptual-Framework.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/SASB-Standards-Application-Guidance-2018-10.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/sasb-taxonomy-2024-11-07.pdf")
# rag_tool.add(data_type="json", source="Standards/SASB_Industry_Data.json")

# # Industry Standards (already existing)
# rag_tool.add(data_type="pdf_file", source="Standards/car-rental-and-leasing-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/insurance-standard_en-gb.pdf")

# # All other SASB Industry Standards
# rag_tool.add(data_type="pdf_file", source="Standards/apparel-accessories-and-footwear-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/appliance-manufacturing-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/building-products-and-furnishings-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/e-commerce-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/household-and-personal-products-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/multiline-and-specialty-retailers-and-distributors-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/toys-and-sporting-goods-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/coal-operations-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/construction-materials-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/iron-and-steel-producers-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/metals-and-mining-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/oil-and-gas-exploration-and-production-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/oil-and-gas-midstream-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/oil-and-gas-refining-and-marketing-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/oil-and-gas-services-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/asset-management-and-custody-activities-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/commercial-banks-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/consumer-finance-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/investment-banking-and-brokerage-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/mortgage-finance-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/security-and-commodity-exchanges-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/agricultural-products-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/alcoholic-beverages-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/food-retailers-and-distributors-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/meat-poultry-and-dairy-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/non-alcoholic-beverages-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/processed-foods-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/restaurants-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/tobacco-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/biotechnology-and-pharmaceuticals-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/drug-retailers-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/health-care-delivery-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/health-care-distributors-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/managed-care-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/medical-equipment-and-supplies-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/electric-utilities-and-power-generators-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/engineering-and-construction-services-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/gas-utilities-and-distributors-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/home-builders-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/real-estate-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/real-estate-services-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/waste-management-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/water-utilities-and-services-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/biofuels-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/forestry-management-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/fuel-cells-and-industrial-batteries-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/pulp-and-paper-products-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/solar-technology-and-project-developers-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/wind-technology-and-project-developers-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/aerospace-and-defence-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/chemicals-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/containers-and-packaging-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/electrical-and-electronic-equipment-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/industrial-machinery-and-goods-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/advertising-and-marketing-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/casinos-and-gaming-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/education-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/hotels-and-lodging-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/leisure-facilities-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/media-and-entertainment-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/professional-and-commercial-services-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/electronic-manufacturing-services-and-original-design-manufacturing-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/hardware-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/internet-media-and-services-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/semiconductors-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/software-and-it-services-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/telecommunication-services-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/air-freight-and-logistics-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/airlines-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/auto-parts-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/automobiles-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/cruise-lines-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/marine-transportation-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/rail-transportation-standard_en-gb.pdf")
# rag_tool.add(data_type="pdf_file", source="Standards/road-transportation-standard_en-gb.pdf")

file_search = CrewaiTool(
    name="file_search",
    description="Performs a semantic search over the complete SASB standards library including all 77 industry standards, SASB Conceptual Framework, Application Guidance, Taxonomy, and industry classification data. Use this tool to find specific information or answer questions based on the content of these comprehensive sustainability disclosure standards.",
    tool=rag_tool
)
